(get-config "config.lsp" :test-prop-2 :dir *subdir*)
(get-config "config.lsp" :common-prop :dir *subdir*)
(get-config "nonexistent-file.lsp" :some-prop :dir *subdir*)
(get-config "nonexistent-file.lsp" :some-prop :dir *subdir*)
(get-config "config.lsp" :test-prop-1 :dir "/tmp/non-existent-dir/")
(get-config (uiop:parse-native-namestring "/tmp/config.lsp") :test-prop-1)
(get-config "empty.lsp" :some-prop :dir *test-temp-dir*)
(get-config "invalid.lsp" :some-prop :dir *test-temp-dir*)
(get-config "config-with-nil.lsp" :nil-prop :dir *test-temp-dir*)
(get-config "config-with-nil.lsp" :some-other-prop :dir *test-temp-dir*)
(get-config "junk.txt" :some-prop :dir *test-temp-dir*)
(get-config "junk.bin" :some-prop :dir *test-temp-dir*)
(get-config1 (merge-pathnames "config.lsp" *subdir*) :test-prop-2)
(get-config1 (merge-pathnames "config.lsp" *subsubdir*) :common-prop)
(get-config1 (merge-pathnames "nonexistent-file.lsp" *subdir*) :some-prop)
(get-config1 (uiop:parse-native-namestring "/tmp/non-existent-dir/non-existent-file.lsp") :some-prop)
(get-config1 *test-file-4* :some-prop)
(get-config1 *test-file-5* :some-prop)
(get-config1 *test-file-6* :nil-prop)
(get-config1 *test-file-6* :some-other-prop)
(get-config1 *test-file-7* :some-prop)
(get-config1 *test-file-8* :some-prop)
